### PR TITLE
Update Elasticsearch Version to 8.5.2

### PR DESCRIPTION
**Pull request by aldidoanta**
# Overview
- Closes https://github.com/SIGmoirelabs/SIGmoirelabs/issues/2.
- ES 8 causes an issue in `grimoirelab-elk`. Therefore, we use a forked repo of `grimoirelab-elk` with some bugfixes, while waiting for the [PR on the main repo](https://github.com/chaoss/grimoirelab-elk/pull/1091) to be merged.

# Known Issues
- `kibiter` does not support ES 8. According to [this statement about `grimoirelab-kibiter`](https://github.com/chaoss/grimoirelab-kibiter/issues/152#issuecomment-1293123931), we cannot rely on Kibiter if we need to use ES 8. We need to use Kibana, and somehow adapt it to the existing `grimoirelab` ecosystem.
- An error message related to enrichment.
```bash
grimoire_elk.elk - ERROR - [git] Problem executing study enrich_onion:git,
RequestError(400, 'x_content_parse_exception', '[1:74] [date_histogram] unknown field [interval] did you mean [fixed_interval]?')
```

### CODE REVIEW

**Review by Rafaeltheraven — APPROVED** [review]

**Comment by TomG777** [comment]
It seems you should be able to use
```yml
      build:
        context: ../docker
        dockerfile: Dockerfile
```
instead in the docker-compose.
That way you don't need to add the `docker/` in front of the stage file in the Dockerfile.
This simplifies things and likely will work towards us breaking less things.

**Comment by aldidoanta** [comment]
> It seems you should be able to use
> 
> ```yaml
>       build:
>         context: ../docker
>         dockerfile: Dockerfile
> ```
> 
> instead in the docker-compose. That way you don't need to add the `docker/` in front of the stage file in the Dockerfile. This simplifies things and likely will work towards us breaking less things.

> 

@TomG777 I tried using that approach, and used this in `Dockerfile`

```Dockerfile
COPY ../requirements.txt ${CONF_DIR}/requirements.txt
```

But Docker complained that the `requirements.txt` is outside the build context
```bash
COPY failed: forbidden path outside the build context: ../requirements.txt ()
```

**Comment by aldidoanta** [comment]
Three possible workarounds:
a. Modify the build context in `docker-compose.yml` and the path to `requirements.txt` in `Dockerfile`. Basically what I'm doing in this PR. Or
b. Move `requirements.txt` into the `docker/` directory. Or
c. Put `docker-compose.yml` and `Dockerfile` in the project root, and delete all the unused docker-compose files.

**Comment by aldidoanta** [comment]
> Three possible workarounds:
> a. Modify the build context in `docker-compose.yml` and the path to `requirements.txt` in `Dockerfile`. Basically what I'm doing in > this PR. Or
> b. Move `requirements.txt` into the `docker/` directory. Or
> c. Put `docker-compose.yml` and `Dockerfile` in the project root, and delete all the unused docker-compose files.

@TomG777 Do you have any further comments about these possible workarounds? Otherwise I'll use my current approach.

**Pull request merged**
